name: Deploy to prod

on:
  push:
    branches:
      master

jobs:
  deploy:
    name: Deploy on production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: yarn install
      - name: 'Build application'
        run: yarn build
      - name: 'Run unit tests'
        run: yarn test --browsers=ChromeHeadless --watch=false
      # BUG WITH CHROME WEBDRIVER
      #- name: 'Run e2e tests'
      #  run: yarn run e2e --webdriver-update
      - name: 'Check lint'
        run: yarn run lint
      - name: 'Deploy to GH-Pages'
        run: |
          PACKAGE_VERSION=$(jq -r ".version" package.json)
          yarn run ng deploy --repo=https://github.com/lbar/lbar.github.io.git --name="Auto-deploy" --email=lbar@users.noreply.github.com --cname=loicbarbier.fr --message="Deploy v${PACKAGE_VERSION}" --branch=master
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
