name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: yarn install
      - name: 'Build application'
        run: yarn build
      - name: 'Run unit tests'
        run: yarn test --browsers=ChromeHeadless --watch=false
      - name: 'Run e2e tests'
        run: yarn run e2e --webdriver-update
      - name: 'Check lint'
        run: yarn run lint
